// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Repositories;

public partial class Sparepartspurchaseorder
{
    public int OrderId { get; set; }

    public int ApplicationId { get; set; }

    public short RequiredItem { get; set; }

    public short RequiredQuantity { get; set; }

    public ulong ApprovedByGeneralSupervisor { get; set; }

    public ulong ApprovedByGeneralManager { get; set; }

    public virtual ApplicationDTO Application { get; set; }

    public virtual Sparepart RequiredItemNavigation { get; set; }
}